### ISSUE TITLE
[CI/CD] unit test are failing for no reason

### ISSUE THREAD

**Issue by avrahamcool** [aurelia/v1#21]
the ci/cd is broken somehow.
every PR is failing at the same tests, regardless of the code changed made in them.
(I'm not familiar enough with this topic to be able to fix this.)

**Comment by 3cp** [comment]
The github actions macOS setup is flaky (probably some network issue).

**Comment by 3cp** [comment]
I don't think there is much we can do about it. The macOS vms are provided by another cloud provider rather than Azure that MS can fully control.

**Comment by avrahamcool** [comment]
should this be closed then?

**Comment by avrahamcool** [comment]
can we turn off those tests only?
they hide important information in the cases we have a real test failure.

**Comment by 3cp** [comment]
I recall I did turn off macOS e2e for few weeks, then turned it back on. I will see if I can set it to "allow failure".

**Comment by 3cp** [comment]
It's mostly `Cypress verification timed out`, there are few related issues in cypress repo but no clear solution.
