### ISSUE TITLE
[scaffolding] idea for using aurelia cli

### ISSUE THREAD

**Issue by avrahamcool** [aurelia/v1#23]
creation of a new project has moved over from `aurelia-cli` to a `makes` based scaffolding (which I totally love).
so, it's convenient to not even have the `au` installed globally anymore.

but  - `au` was also in charge of scaffolding new assets in the project (like `value-converters` etc.)
all of the generators are included in the project itself, and `aurelia-cli` is also installed locally in the project.
but without a global installation of `au`, we don't have an entry point for running those generators.
so it's seems we still have to install `au` globally just for generators and tasks anyway..
the responsibility of the global `au` is just to find the local version of `au` and run with it..

but: this can be easily be done by adding a new script to the `npm` scripts:

```javascript
"scripts": {
		"build": "webpack --env.production --extractCss",
		"start": "webpack-dev-server --extractCss",
		"build:dev": "webpack --extractCss",
		"analyze": "webpack --env.production --analyze",
		"au": "au" //<--- add this
	}
```

now, we can run `npm run au generate ...` without having `aurelia-cli` installed globally.
`npm` will will pick-up the local installation of `aurelia-cli`, and everything continue like before.

is this what you also do in your projects?
is this a valid PR to make?

**Comment by 3cp** [comment]
I think `npm run au generate` does not work, you have to do `npm run au -- generate`.

Alternatively, you don't need to add anything. `npx au generate` will just work.

`npx xxx` will search local bin `xxx` first, then try globally installed bin `xxx`, then try fetching remote package `xxx`. So `npx au ...` will just use your local bin `au`.

This is the same trick why `npx makes ...` works without any installation, it fetches remote package `makes` automatically.

**Comment by avrahamcool** [comment]
> I think `npm run au generate` does not work, you have to do `npm run au -- generate`.

I do `npm run au generate` in my projects, and it works. (windows 10 machine, regular cmd).

> Alternatively, you don't need to add anything. `npx au generate` will just work.
didn't know about this one. definatly a better solution.
thank you.

**Comment by 3cp** [comment]
BTW I would also like aurelia vscode plugin to implement all those generators, can be a context menu click in any folder.

**Comment by 3cp** [comment]
> I do `npm run au generate` in my projects, and it works. (windows 10 machine, regular cmd).

Good to know, it worked for me too. It was probably my previous experience with outdated npm version.

**Comment by zewa666** [comment]
@3cp the official Aurelia vscode Extension does make use of generate already
