### ISSUE TITLE
Missing option to skip unit testing

### ISSUE THREAD

**Issue by avrahamcool** [aurelia/v1#9]
There in no longer an option for skiping unit testing.
[this is also the case when creating a Plugin]

is this by design?

![image](https://user-images.githubusercontent.com/5445320/91904813-3c65f180-ecae-11ea-9eb8-a2da18a19e92.png)

**Comment by 3cp** [comment]
Yes, that option is removed to shorten e2e test for this repo.

**Comment by avrahamcool** [comment]
having to choose a unit test suits adds a lot of dependencies to the project.
although testing is important, not all applications use it.

I think this option should be back. (and set the default to "no unit test" - just like before).

**Comment by 3cp** [comment]
Agreed.

**Comment by avrahamcool** [comment]
Thank you very much.
creating a new project with the "none" option still bring all the test dependencies in the package.json

:(

**Comment by 3cp** [comment]
I only saw `aurelia-testing`, is that what you mean? The `aurelia-testing` is also used in dev mode, not just in test, so we cannot remove it.

If you remove it from your project, you need to remove the line in `src/main.js` too.

**Comment by avrahamcool** [comment]
You are right.

I've must have made a mistake somehow.
sorry for not double checking.
